[package]
name = "hyeong"
version = "0.1.0"
authors = ["VBChunguk <chwo9843@gmail.com>"]

[features]
big-rational = []

[dependencies]
num = "0.1.36"

[dependencies.clap]
version = "~2.20.1"
default-features = false
features = ["color", "wrap_help", "yaml"]
