[package]
name = "rshyeong"
version = "0.1.0"
authors = ["Wonwoo Choi <chwo9843@gmail.com>"]

[features]
big-rational = []

[dependencies.num]
version = "0.1.36"
default-features = false
features = ["bigint", "rational"]

[dependencies.clap]
version = "~2.20.1"
default-features = false
features = ["color", "wrap_help", "yaml"]
